# Generated by Django 4.0.5 on 2022-06-29 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desc', models.TextField(max_length=999)),
                ('is_tutor_home', models.BooleanField(default=False)),
                ('is_student_home', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.city')),
            ],
        ),
    ]
