# Generated by Django 4.0.5 on 2022-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_slug', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('desc', models.TextField(max_length=999)),
            ],
        ),
    ]
