# Generated by Django 4.0.5 on 2022-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_subject_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='desc',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
