# Generated by Django 4.0.5 on 2022-06-29 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[(1, 'Failure'), (2, 'Bad'), (3, 'Satisfactorily'), (4, 'Good'), (5, 'Great')], default=5, max_length=1)),
                ('created', models.DateTimeField(editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
            ],
        ),
    ]
